spring:
  profiles:
    active: ${DBS_ACTIVE_PROFILE:live}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

logging:
  level:
    root: INFO

backbase:
  security:
    public:
      paths: /**
  api:
    simulator:
      refreshSchedule: "*/30 * * * * *"
      prismPath: /bin/prism
      basePath: /
      mode: SIMULATION

management:
  endpoint:
    health:
      show-details: always
      show-components: always
  health:
    rabbit:
      enabled: false
  server:
    port: 24080
