spring:
  profiles:
    active: ${DBS_ACTIVE_PROFILE:live}
  autoconfigure:
    exclude: org.springframework.boot.autoconfigure.web.servlet.error.ErrorMvcAutoConfiguration

logging:
  level:
    root: INFO

backbase:
  security:
    public:
      paths: /**
  api:
    simulator:
      refreshSchedule: "*/30 * * * * *"
      prismPath: /bin/prism
      specAuthorization: YmFja2Jhc2U6YTZjMmhTbVRyOEw1NUdkOQ==
      mode: SIMULATION

management:
  health:
    rabbit:
      enabled: false
  server:
    port: 24080
