# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

# name: Java CI with Maven

# name: Manual workflow
# on:
#   pull_request:
#     types: [labeled]
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]   

jobs:
  build:
    name: On Label
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Cache local Maven repository
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: 11
        server-id: backbase
        server-username: MAVEN_USERNAME
        server-password: MAVEN_PASSWORD
    - name: Build and test project
      run: mvn clean verify --file pom.xml
      env:
        MAVEN_USERNAME: ${{ secrets.MAVEN_USERNAME }}
        MAVEN_PASSWORD: ${{ secrets.MAVEN_PASSWORD }}
